### ISSUE TITLE
Suggestion: Add Search Functionality

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#12]
[v2.4.5](https://github.com/Neop/mudmap2/releases/tag/v2.4.5)

Initially, just to get something out:
- [ ] Search would search (simple contains match, case insensitive) Name and Comments in the current map.

Ideally:
- [ ] Search dialog would have option for searching Current Map Only or Current World.  Searchable fields (Name/Comments/etc) would be includable/excludable maybe via check box.

My Thoughts:
- I'd say start searching at the currently selected cell (or top left cell if none is selected), searching left to right, then moving down and repeating left to right.
- For my use, I don't see the need for regex, but I see no reason not to allow it.
- The Place containing the search match would be Selected and maybe centered.
- **Ctrl+F** for Search dialog.  **F3** for Next Match.

**Comment by Neop** [comment]
- Can you clarify your thought on the search order? The current implementation does a search on unordered lists of places of each separate layer (restricting search to a single layer should be a minor change).
- Adding some kind of "advanced search dialog" might be an option. I think the results should be shown in a subsequent dialog, selecting a result entry will center and select the place.
- Regex shouldn't be a big issue either (maybe a check box to enable it).

**Comment by avatard** [comment]
Sorry, I hadn't touched MUD Map for several months until today.

I didn't see the search option at the bottom right.  My bad.

I would probably use an ordered list for search results though?  I ran into a situation at work a while back where unordered search results caused some serious confusion during review/change boards.

I noticed that when I'm mapping, I'm working on a particular "Map" and adding "Places." (obviously, yes)  If I create a Place in MUDMap, then go NW in my particular game, I'll first search my current MUDMap Map to ensure that the Place does not already exist.  I frequently run into scenarios in my game where going a cardinal direction and then the reverse cardinal direction doesn't necessarily take you back where you started.  Does that make sense?

**Comment by Neop** [comment]
Yes, that makes sense to me.
The maps and places lists are in fact ordered lists (not sure why I said otherwise in the previous comment), but I noticed that upper and lower case are not ignored (in sorting). Say you have three places "A", "b" and "C" they will be ordered "A", "C", "b". Can you confirm that this is the issue you ran into or is it something else?

**Comment by avatard** [comment]
I didn't notice the case sensitivity/ACb issue, though I have also done that at work too. LOL!

The existing search works OK.  It's just a little un-intuitive.  Instead of spending time on a new dialog, I might do something like: 1) CTRL-F to focus on the search box, and 2) ESC to clear the search box/results and return focus to Map/Place.

Complex search/regex like I mentioned before is probably overkill.

Edit: I'd probably prefer defaulting to a Place search instead of a Map search.

**Comment by avatard** [comment]
Just to clarify, my original issue was that I didn't know there was an existing search option.  Sorry about that

**Comment by Neop** [comment]
Don't worry, it made me find the case sensitivity issue.
I've fixed that and added the keyboard shortcuts (ESC only if the search box is focused since it's also used to reset selections on the map). I'll publish a new release in a few days.

On default place search / map search.. While place search is probably used more often than map search I think the map side bar is more useful as  an overview when you just opened a world file (especially for first time users). It's just one click to switch anyway.
