### ISSUE TITLE
How to move places?

### ISSUE THREAD

**Issue by denizzzka** [Neop/mudmap2#22]

**Comment by Neop** [comment]
If you want to move a single place:
- do a right click on a place, then click 'cut place' in the context menu
- do a right click on a free space on the map and click 'paste' in the context menu

If you want to move more than one place at once:
- make sure the red place cursor is enabled (World menu, check 'Show place cursor')
- select multiple places by ctrl+click or shift+click for a box selection.
- do ctrl+c OR click copy in the context menu to copy the place
- do a single left click on a free spot on the map. The blue cursors show where the places will be inserted
- do ctrl+v OR click paste in the context menu to move the places

The same goes for duplicating place (copy+paste). Also, please make sure to save your world before moving places since it can not be undone.

**Comment by denizzzka** [comment]
> The same goes for duplicating place (copy+paste). Also, please make sure to save your world before moving places since it can not be undone.

It is terrible :-)

**Comment by Neop** [comment]
I know.. I'm trying to find a good way to improve that but I wouldn't expect it soon :/
