### ISSUE TITLE
mudmap2  how to use Sub-areas 

### ISSUE THREAD

**Issue by leonlau** [Neop/mudmap2#31]

**Comment by Neop** [comment]
What version of mudmap do you use?

I'm asking because I replaced the term "Sub-area" with "map" since it's basically that. Think of a map in a book of maps (which is I call 'world' in mudmap).

So, my suggestion is to create one map and, say you can enter buildings or areas that are more detailed than their surrounding, create a new map (aka sub-area) for that and link it with a place on the base map. Another way to think of it: Create a map of countries where each place represents a country. You can link these to maps for each country where you have places for towns and the stuff between them. Then you could do maps for each town, those maps countain streets and buildings... Like I said, sub-areas is just a term for this that I changed with version 2.3.0.

I hope this answers your question, tell me if you got any other!

**Comment by leonlau** [comment]
thank you for your reply!
I am using the master build, I see the word "Sub-area" in the v1 version of the doc.
I want to create a hierarchical world, for example, in the world map, a tile represents a country.
Sub-map into this country, A tile represents a state or province, entering a sub-map of the province. A tile represents a town.
How to connect tiles in two maps?

**Comment by Neop** [comment]
Do a right click on the first place to connect, select "Maps" in the context menu, then click "Connect with existing place" if the sub-map already exists (you will then be able to chose the second place to connect) or click "New place on new map" to create a new sub-map.
Once you have connected two places you'll find a new entry in the Maps context menu that will get you to the other place.
