### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by Roxor007** [Neop/mudmap2#37]
Hi, I am looking for some standard format for our mud maps in our guild. I am glad to see someone is working on such tool. (our 20+ years handwriten maps look a bit outdated :-) )
So, I was wondering if there is any way to display Comment field on tile (something like world settings for room id) . All i see is letters Co when i insert comment but not actual content of it.
I could really use that information , when connecting 2 maps. For example you want to connect ground floor of map (map 1) with 1st floor (map 2) and u want to say those floors are connected via hidden exit "enter statue". At the moment I have to name 1st room of Map 2 "Enter statue" to see "Ch: enter statue" on map1. But i want to use that name for something else :-(
Any chance to add that option or I am missing some existing option for this?

**Comment by Neop** [comment]
Thanks for your suggestion, I just added the comment text to the place tiles and released a new version: https://github.com/Neop/mudmap2/releases/tag/v2.5.5 I hope it works as you expect since there isn't much space on those tiny tiles. Tell me if you got other suggestions to improve this feature.

I also changed the Ch (child) and Pa (parent) mark to M (map) since I guess my concepts might not be intuitive, it's just meant as a note like 'here's a link to another map, going to place X'
