### ISSUE TITLE
Bug: Export as HTML, script src

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#8]
[v2.4.5](https://github.com/Neop/mudmap2/releases/tag/v2.4.5)
When exporting as html to an alternate directory, the html file includes script src=http://maps.gaardian.com/wz_jsgraphics.js, but gaardian.com does not resolve.

**Comment by Neop** [comment]
Thanks for your feedback!
I tried it yesterday and today. The URL works for me, both for an exported map and when I load the script with my web browser. I can only suspect problems with the server or a blocked connection to your system (for any reason).

On another note: Is HTML export a relevant feature? It was a user request, but I've been considering to remove it since it is barely maintainable for me and I prefer to go back to a more stable state of features.

**Comment by avatard** [comment]
I'm behind a VPN so maybe that's my issue. I didn't think to disable the
VPN and give it a shot.

Export HTML sounds neat, but there probably isn't much use for it.

**Comment by avatard** [comment]
It looks to be inaccessible via [PIA](https://www.privateinternetaccess.com).  Just FYI.

**Comment by Neop** [comment]
I suspect the problem to be caused by the VPN and / or the server.
I will remove HTML export in the next release since it's barely maintainable. If the feature gets reintroduced in a future release it should not use external resources and be more adapted to MUD Map's features.
